name: Upload Prebuilt Artifacts to Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare latest-named copies
        run: |
          VERSION="${GITHUB_REF##*/}"
          VERSION_NUM="${VERSION#v}"

          echo "Detected version: $VERSION_NUM"

          mkdir -p release/latest

          cp release/crossdesk-windows-x86_64-v${VERSION_NUM}.exe release/latest/crossdesk-windows-x86_64-latest.exe
          cp release/crossdesk-macos-x86_64-v${VERSION_NUM}.pkg   release/latest/crossdesk-macos-x86_64-latest.pkg
          cp release/crossdesk-macos-aarch64-v${VERSION_NUM}.pkg   release/latest/crossdesk-macos-aarch64-latest.pkg
          cp release/crossdesk-linux-x86_64-v${VERSION_NUM}.deb   release/latest/crossdesk-linux-x86_64-latest.deb

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          files: |
            release/crossdesk-windows-x86_64-v*.exe
            release/crossdesk-macos-x86_64-v*.pkg
            release/crossdesk-macos-aarch64-v*.pkg
            release/crossdesk-linux-x86_64-v*.deb
            release/latest/crossdesk-windows-x86_64-latest.exe
            release/latest/crossdesk-macos-x86_64-latest.pkg
            release/latest/crossdesk-macos-aarch64-latest.pkg
            release/latest/crossdesk-linux-x86_64-latest.deb
